### ISSUE TITLE
RuntimeError: result type Float can't be cast to the desired output type Long

### ISSUE THREAD

**Issue by animesh-007** [verashira/TSPNet#4]
````
epoch 001:   0% 0/111 [00:00<?, ?it/s]/content/drive/My Drive/TSPNet/fairseq/optim/adam.py:179: UserWarning: This overload of add_ is deprecated:
	add_(Number alpha, Tensor other)
Consider using one of the following signatures instead:
	add_(Tensor other, *, Number alpha) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  exp_avg.mul_(beta1).add_(1 - beta1, grad)
epoch 001 | loss 9.643 | nll_loss 9.33 | ppl 643.732 | wps 22.2 | ups 0.02 | wpb 1212.8 | bsz 63.9 | num_updates 111 | lr 0.0001 | gnorm 1.309 | clip 0 | oom 0 | train_wall 5912 | wall 6050
epoch 001 | valid on 'test' subset:   0% 0/10 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 11, in <module>
    cli_main()
  File "/content/drive/My Drive/TSPNet/fairseq_cli/train.py", line 323, in cli_main
    main(args)
  File "/content/drive/My Drive/TSPNet/fairseq_cli/train.py", line 105, in main
    valid_losses = validate(args, trainer, task, epoch_itr, valid_subsets)
  File "/content/drive/My Drive/TSPNet/fairseq_cli/train.py", line 250, in validate
    trainer.valid_step(sample)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/content/drive/My Drive/TSPNet/fairseq/trainer.py", line 452, in valid_step
    raise e
  File "/content/drive/My Drive/TSPNet/fairseq/trainer.py", line 437, in valid_step
    sample, self.model, self.criterion
  File "/content/drive/My Drive/TSPNet/fairseq/tasks/translation_sign.py", line 239, in valid_step
    bleu, hyps, refs = self._inference_with_bleu(self.sequence_generator, sample, model)
  File "/content/drive/My Drive/TSPNet/fairseq/tasks/translation_sign.py", line 304, in _inference_with_bleu
    gen_out = self.inference_step(generator, [model], sample, None)
  File "/content/drive/My Drive/TSPNet/fairseq/tasks/fairseq_task.py", line 309, in inference_step
    return generator.generate(models, sample, prefix_tokens=prefix_tokens)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/content/drive/My Drive/TSPNet/fairseq/sequence_generator.py", line 92, in generate
    return self._generate(model, sample, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/content/drive/My Drive/TSPNet/fairseq/sequence_generator.py", line 361, in _generate
    scores.view(bsz, beam_size, -1)[:, :, :step],
  File "/content/drive/My Drive/TSPNet/fairseq/search.py", line 81, in step
    torch.div(self.indices_buf, vocab_size, out=self.beams_buf)

RuntimeError: result type Float can't be cast to the desired output type Long
````

I was trying to run the code in Google Colaboratory but I am getting this error. Can you guide me on how to solve this?

**Comment by verashira** [comment]
It is an issue in `fairseq` that a recent change in PyTorch has deprecated `torch.div` for type casting.
You can try use pytorch<1.6 or change that line of exception to
```python
self.beams_buf = self.indices_buf // vocab_size
```

Refer to: [https://github.com/pytorch/fairseq/commit/f0a61a2774aff2efbc1adb0b5daee346a8401605#diff-5839f0eaef65584df87188720a27a2aa88cf2a51d97459707019c7effa6cefa7R78](https://github.com/pytorch/fairseq/commit/f0a61a2774aff2efbc1adb0b5daee346a8401605#diff-5839f0eaef65584df87188720a27a2aa88cf2a51d97459707019c7effa6cefa7R78)

**Comment by animesh-007** [comment]
> It is an issue in `fairseq` that a recent change in PyTorch has deprecated `torch.div` for type casting.
> You can try use pytorch<1.6 or change that line of exception to
> 
> ```python
> self.beams_buf = self.indices_buf // vocab_size
> ```
> 
> Refer to: [pytorch/fairseq@f0a61a2#diff-5839f0eaef65584df87188720a27a2aa88cf2a51d97459707019c7effa6cefa7R78](https://github.com/pytorch/fairseq/commit/f0a61a2774aff2efbc1adb0b5daee346a8401605#diff-5839f0eaef65584df87188720a27a2aa88cf2a51d97459707019c7effa6cefa7R78)

Thank you for helping. It solved the issue.
